Handle discovery mode packet forwarder tx timeout more gracefully.
helium/miner pull request #1059
Opened 2021-09-14 22:28 UTC by ke6jjj

It's possible, though usually rare, that the request to transmit a
discovery mode beacon packet might time out. When this happens, make sure
not to crash the entire discovery mode session but simply move on to the
next packet.

Should fix #1058, discovered by @maco2035

2021-09-14 23:15 UTC, JayKickliter requested changes
Can you check if handling `{warning, any()}` is needed here?

2021-09-14 23:27 UTC, ke6jjj commented
Sure! I can try to statically analyze if that's possible. There are some other `{error,` cases that can arise, but they all seem unrecoverable and crash worthy.

2021-09-14 23:30 UTC, JayKickliter commented
Ok. I trust your judgment. Add another comment when you decide one way or the other and I'll approve

2021-09-14 23:31 UTC, ke6jjj commented
It's actually a good thing to visit. I get where you're coming from; `send_poc` is marked as returning `{warning, any()}` in the spec. And sure enough, maybe we should also handle the possibility that the transmit power was reduced:

`{warning, {tx_power_corrected, ...}}`

2021-09-14 23:33 UTC, JayKickliter commented
I can certainly imagine a `tx_power_corrected` bug creeping in in the future

2021-09-14 23:39 UTC, ke6jjj commented
Updated to handle `{warning, _}` as well!

2021-09-15 03:50 UTC, JayKickliter approved these changes

2021-09-15 20:22 UTC, Vagabond approved these changes

2021-09-15 20:22 UTC, merged