check a GW has valid capabillity before starting POC
helium/miner pull request #708
Opened 2021-03-26 16:34 UTC by andymck

2021-04-14 18:27 UTC, evanmcc commented on src/poc/miner_poc_statem.erl
>  -include_lib("blockchain/include/blockchain_vars.hrl").
can we take care of this in the init instead?  rather than doing all this stuff, just don't even register for events if we're not capable of handling them.

2021-04-14 18:28 UTC, evanmcc requested changes
I think that this is ready pending the core side, but I think that it'd be simpler just to not init the poc statem (not even starting it would be better, but hard to do in testing with indeterminite chain states) to follow chain events unless we have the proper capability.

2021-04-19 12:49 UTC, andymck commented
> I think that this is ready pending the core side, but I think that it'd be simpler just to not init the poc statem (not even starting it would be better, but hard to do in testing with indeterminite chain states) to follow chain events unless we have the proper capability.

I did consider that approach but as this evolves the light GWs will be allowed to witness.  As such the implemented approach allows for such changes with minimal additions.

2021-05-10 16:47 UTC, evanmcc approved these changes

2021-05-10 16:52 UTC, merged